FROM node:10.13-alpine as builder
WORKDIR '/app'
COPY ./client/package.json ./
RUN npm install
COPY ./client .
RUN npm run build

FROM nginx:mainline-alpine-perl
EXPOSE 4200
COPY ./client/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/todo-app /usr/share/nginx/html